export const styles = {
  app: {
    display: "flex",
    flexDirection: "column",
    height: "100vh",
    maxHeight: "100dvh",
    maxWidth: 420,
    margin: "0 auto",
    background: "var(--color-bg)",
    position: "relative",
    overflow: "hidden",
  },
  content: {
    flex: 1,
    overflowY: "auto",
    paddingBottom: "calc(72px + env(safe-area-inset-bottom))",
  },
  screen: {
    padding: "20px 20px 20px",
  },
  topBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "calc(16px + env(safe-area-inset-top)) 12px 16px",
    background: "var(--color-surface-4)",
    borderBottom: "1px solid var(--color-border)",
    flexShrink: 0,
  },
  topBarTitle: {
    fontSize: 17,
    fontWeight: 600,
    color: "var(--color-text-primary)",
    margin: 0,
    textAlign: "center",
    flex: 1,
  },
  topBarBackButton: {
    width: 36,
    height: 36,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "none",
    border: "none",
    color: "var(--color-text-primary)",
    cursor: "pointer",
    borderRadius: 8,
  },
  topBarSpacer: {
    width: 36,
    height: 36,
    flexShrink: 0,
  },
  secondaryBar: {
    position: "sticky",
    top: 0,
    zIndex: 5,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    padding: "10px 12px",
    background: "var(--color-surface-2)",
    borderBottom: "1px solid var(--color-border)",
  },
  secondaryBarPlaceholder: {
    fontSize: 13,
    fontWeight: 600,
    letterSpacing: 0.5,
    color: "var(--color-text-secondary)",
    textTransform: "uppercase",
  },
  secondaryBarSubtitle: {
    fontSize: 11,
    color: "var(--color-text-tertiary)",
  },
  // 100vh minus the persistent top bar (~68px), this secondary toolbar
  // (~54px now that it shows two lines), and the climb action bar that
  // replaces the tab bar on this page (~110px, taller than the regular
  // tab bar to fit the attempts counter and log-ascent button) — so the
  // image fills exactly the remaining screen height.
  imageStage: {
    height:
      "calc(100vh - 236px - env(safe-area-inset-top) - env(safe-area-inset-bottom))",
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    background: "var(--color-surface-1)",
    touchAction: "none",
  },
  imagePlaceholder: {
    width: "78%",
    maxWidth: 320,
    aspectRatio: "3 / 4",
    borderRadius: 16,
    background: "linear-gradient(155deg, var(--color-surface-6) 0%, var(--color-surface-3) 100%)",
    border: "1px solid var(--color-border-strong)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    userSelect: "none",
    willChange: "transform",
  },
  climbPhoto: {
    width: "100%",
    height: "100%",
    objectFit: "contain",
    userSelect: "none",
    willChange: "transform",
  },
  button: {
    width: "100%",
    padding: "12px 16px",
    borderRadius: 10,
    border: "none",
    background: "var(--color-accent)",
    color: "var(--color-text-primary)",
    fontSize: 15,
    fontWeight: 600,
    cursor: "pointer",
  },
  list: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  listRow: {
    background: "var(--color-surface-5)",
    border: "1px solid var(--color-border)",
    borderRadius: 12,
    padding: "14px 16px",
  },
  listRowLink: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    textAlign: "left",
    background: "var(--color-surface-5)",
    border: "1px solid var(--color-border)",
    borderRadius: 12,
    padding: "14px 16px",
    cursor: "pointer",
    font: "inherit",
  },
  wallRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    height: 72,
    flexShrink: 0,
    textAlign: "left",
    background: "var(--color-surface-5)",
    border: "none",
    borderBottom: "1px solid var(--color-border)",
    borderRadius: 0,
    padding: "14px 16px",
    cursor: "pointer",
    font: "inherit",
  },
  // Two-line variant of wallRow used by ManageRolesScreen: the role select
  // needs room to sit next to the username, and the reset-password action
  // needs its own line below rather than fighting that select for space.
  adminUserRow: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    width: "100%",
    textAlign: "left",
    background: "var(--color-surface-5)",
    borderBottom: "1px solid var(--color-border)",
    padding: "14px 16px",
  },
  adminUserRowTop: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    gap: 12,
  },
  resetPasswordButton: {
    alignSelf: "flex-end",
    background: "none",
    border: "none",
    color: "var(--color-danger)",
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
    padding: 0,
  },
  formSuccess: {
    fontSize: 13,
    color: "var(--color-text-secondary)",
    margin: 0,
  },
  archiveBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    flexShrink: 0,
    textAlign: "left",
    background: "var(--color-surface-2)",
    border: "none",
    borderTop: "1px solid var(--color-border)",
    borderRadius: 0,
    padding: "14px 16px",
    color: "var(--color-text-secondary)",
    fontSize: 15,
    fontWeight: 500,
    cursor: "pointer",
    font: "inherit",
  },
  archiveSetRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    flexShrink: 0,
    textAlign: "left",
    background: "var(--color-surface-0)",
    border: "none",
    borderTop: "1px solid var(--color-border)",
    borderRadius: 0,
    padding: "12px 20px",
    cursor: "pointer",
    font: "inherit",
  },
  climbRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    textAlign: "left",
    background: "var(--color-surface-5)",
    border: "none",
    borderBottom: "1px solid var(--color-border)",
    borderRadius: 0,
    padding: "14px 16px",
    cursor: "pointer",
    font: "inherit",
  },
  climbRowLeft: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 2,
  },
  climbRowRight: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    gap: 2,
  },
  climbDifficulty: {
    fontSize: 17,
    fontWeight: 700,
    color: "var(--color-text-primary)",
  },
  climbStars: {
    display: "flex",
    alignItems: "center",
    gap: 1,
  },
  climbAscents: {
    fontSize: 12,
    color: "var(--color-text-tertiary)",
  },
  climbTitle: {
    fontSize: 15,
    fontWeight: 600,
    color: "var(--color-text-primary)",
  },
  climbSetter: {
    fontSize: 12,
    color: "var(--color-text-tertiary)",
  },
  commentHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  commentAuthor: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--color-text-primary)",
    margin: 0,
  },
  commentDeleteButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "none",
    border: "none",
    color: "var(--color-text-tertiary)",
    cursor: "pointer",
    padding: 2,
  },
  commentText: {
    fontSize: 14,
    color: "var(--color-text-secondary)",
    lineHeight: 1.5,
    margin: 0,
  },
  listTitle: {
    fontSize: 15,
    fontWeight: 500,
    color: "var(--color-text-primary)",
    margin: "0 0 4px",
  },
  listMeta: {
    fontSize: 13,
    color: "var(--color-text-tertiary)",
    margin: 0,
  },
  placeholderText: {
    fontSize: 15,
    color: "var(--color-text-tertiary)",
    marginBottom: 20,
  },
  profileHeaderRow: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: 28,
  },
  profileLeft: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 4,
  },
  avatar: {
    width: 56,
    height: 56,
    borderRadius: "50%",
    background: "var(--color-accent)",
    color: "var(--color-text-primary)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 18,
    fontWeight: 700,
    marginBottom: 8,
  },
  avatarImage: {
    width: 56,
    height: 56,
    borderRadius: "50%",
    objectFit: "cover",
    marginBottom: 8,
  },
  avatarPreview: {
    width: 96,
    height: 96,
    borderRadius: "50%",
    objectFit: "cover",
    alignSelf: "center",
  },
  avatarPreviewPlaceholder: {
    width: 96,
    height: 96,
    borderRadius: "50%",
    background: "var(--color-surface-5)",
    border: "1px solid var(--color-border)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
  },
  pickImageButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "10px 16px",
    borderRadius: 10,
    border: "1px solid var(--color-border)",
    background: "transparent",
    color: "var(--color-text-offwhite)",
    fontSize: 14,
    fontWeight: 500,
    cursor: "pointer",
    textAlign: "center",
  },
  profileUsername: {
    fontSize: 16,
    fontWeight: 600,
    color: "var(--color-text-primary)",
    margin: 0,
  },
  profileDisplayName: {
    fontSize: 13,
    color: "var(--color-text-tertiary)",
    margin: 0,
  },
  profileRight: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 12,
  },
  profileStatsRow: {
    display: "flex",
    gap: 28,
  },
  settingsButton: {
    width: "100%",
    background: "none",
    border: "none",
    borderBottom: "1px solid var(--color-border)",
    borderRadius: 0,
    padding: "6px 0",
    color: "var(--color-text-secondary)",
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
    font: "inherit",
  },
  followButton: {
    width: "100%",
    background: "none",
    border: "none",
    borderBottom: "1px solid var(--color-accent-bright)",
    borderRadius: 0,
    padding: "6px 0",
    color: "var(--color-accent-bright)",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    font: "inherit",
  },
  profileStat: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 2,
  },
  profileStatButton: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 2,
    background: "none",
    border: "none",
    padding: 0,
    cursor: "pointer",
    font: "inherit",
  },
  profileStatNumber: {
    fontSize: 18,
    fontWeight: 700,
    color: "var(--color-text-primary)",
  },
  profileStatLabel: {
    fontSize: 12,
    color: "var(--color-text-tertiary)",
  },
  gradeChartWrapper: {
    marginBottom: 20,
  },
  gradeChartTitle: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--color-text-secondary)",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    margin: "0 0 12px",
  },
  gradeChart: {
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: 2,
  },
  leaderboardRow: {
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
    gap: 12,
  },
  leaderboardColumn: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    flex: 1,
    background: "none",
    border: "none",
    padding: 0,
    cursor: "pointer",
    font: "inherit",
  },
  leaderboardUsername: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--color-text-primary)",
    margin: 0,
  },
  leaderboardName: {
    fontSize: 11,
    color: "var(--color-text-tertiary)",
    margin: 0,
  },
  leaderboardAscents: {
    fontSize: 12,
    fontWeight: 600,
    color: "var(--color-text-secondary)",
    margin: "4px 0 8px",
  },
  leaderboardPodiumBlock: {
    width: "100%",
    borderRadius: "8px 8px 0 0",
    border: "1px solid var(--color-border-strong)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  leaderboardPodiumRank: {
    fontSize: 18,
    fontWeight: 700,
    color: "var(--color-text-primary)",
  },
  gradeBarColumn: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 4,
  },
  gradeBarCount: {
    fontSize: 9,
    color: "var(--color-text-tertiary)",
    lineHeight: 1,
    minHeight: 9,
  },
  gradeBarsRow: {
    flex: 1,
    position: "relative",
    display: "flex",
    alignItems: "flex-end",
    gap: 2,
  },
  gradeGridlines: {
    position: "absolute",
    top: 13,
    left: 0,
    right: 0,
    height: 80,
    pointerEvents: "none",
    // Solid horizontal lines at 0/25/50/75/100% of the track height,
    // drawn once across the full width so they read as continuous lines
    // rather than being broken up by the gaps between bars.
    backgroundImage:
      "linear-gradient(var(--color-border), var(--color-border)), linear-gradient(var(--color-border), var(--color-border)), linear-gradient(var(--color-border), var(--color-border)), linear-gradient(var(--color-border), var(--color-border))",
    backgroundSize: "100% 1px",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "top 0 left 0, bottom 25% left 0, bottom 50% left 0, bottom 75% left 0",
  },
  gradeBarTrack: {
    height: 80,
    width: "100%",
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
    position: "relative",
  },
  gradeBar: {
    width: "70%",
    background: "var(--color-accent)",
    borderRadius: "3px 3px 0 0",
  },
  gradeBarSkeleton: {
    background: "var(--color-border)",
  },
  gradeBarLabel: {
    fontSize: 9,
    color: "var(--color-text-tertiary)",
    lineHeight: 1,
    minHeight: 9,
  },
  gradeAxisColumn: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    gap: 4,
    paddingRight: 6,
    flexShrink: 0,
  },
  gradeAxisSpacer: {
    minHeight: 9,
  },
  gradeAxisTrack: {
    height: 80,
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  gradeAxisLabel: {
    fontSize: 9,
    color: "var(--color-text-muted)",
    lineHeight: 1,
  },
  logbookButton: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "12px 16px",
    borderRadius: 0,
    border: "none",
    borderTop: "1px solid var(--color-border)",
    borderBottom: "1px solid var(--color-border)",
    background: "transparent",
    color: "var(--color-text-offwhite)",
    fontSize: 15,
    fontWeight: 500,
    cursor: "pointer",
  },
  savedClimbsButton: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "12px 16px",
    borderRadius: 0,
    border: "none",
    borderTop: "1px solid var(--color-border)",
    background: "transparent",
    color: "var(--color-text-offwhite)",
    fontSize: 15,
    fontWeight: 500,
    cursor: "pointer",
  },
  logoutButton: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    padding: "12px 16px",
    borderRadius: 0,
    border: "none",
    borderBottom: "1px solid var(--color-border)",
    background: "transparent",
    color: "var(--color-text-offwhite)",
    fontSize: 15,
    fontWeight: 500,
    cursor: "pointer",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
  },
  modeToggle: {
    display: "flex",
    background: "var(--color-surface-5)",
    border: "1px solid var(--color-border)",
    borderRadius: 10,
    padding: 4,
    marginBottom: 20,
    gap: 4,
  },
  modeButton: {
    flex: 1,
    padding: "8px 0",
    borderRadius: 8,
    border: "none",
    background: "transparent",
    color: "var(--color-text-tertiary)",
    fontSize: 14,
    fontWeight: 500,
    cursor: "pointer",
  },
  modeButtonActive: {
    background: "var(--color-surface-7)",
    color: "var(--color-text-primary)",
  },
  label: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    fontSize: 13,
    color: "var(--color-text-tertiary)",
  },
  checkboxRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13,
    color: "var(--color-text-tertiary)",
  },
  checkboxInput: {
    width: 18,
    height: 18,
    accentColor: "var(--color-accent)",
  },
  input: {
    background: "var(--color-surface-5)",
    border: "1px solid var(--color-border)",
    borderRadius: 10,
    padding: "10px 12px",
    fontSize: 15,
    color: "var(--color-text-primary)",
    outline: "none",
  },
  searchInput: {
    display: "block",
    width: "calc(100% + 40px)",
    boxSizing: "border-box",
    marginLeft: -20,
    marginRight: -20,
    borderRadius: 0,
    borderLeft: "none",
    borderRight: "none",
  },
  climbsFilterRow: {
    display: "flex",
    gap: 8,
    marginBottom: 20,
  },
  climbsFilterInput: {
    flex: 1,
    background: "var(--color-surface-5)",
    border: "1px solid var(--color-border)",
    borderRadius: 10,
    padding: "10px 12px",
    fontSize: 15,
    color: "var(--color-text-primary)",
    outline: "none",
  },
  climbsFilterButton: {
    width: 42,
    height: 42,
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "var(--color-surface-5)",
    border: "1px solid var(--color-border)",
    borderRadius: 10,
    color: "var(--color-text-secondary)",
    cursor: "pointer",
  },
  inputInvalid: {
    border: "1px solid var(--color-danger)",
  },
  inputDisabled: {
    color: "var(--color-text-muted)",
    cursor: "not-allowed",
  },
  formError: {
    fontSize: 13,
    color: "var(--color-danger)",
    margin: 0,
  },
  asyncError: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 12,
    padding: "24px 20px",
  },
  retryButton: {
    padding: "8px 20px",
    borderRadius: 8,
    border: "1px solid var(--color-border-strong)",
    background: "var(--color-surface-4)",
    color: "var(--color-text-primary)",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
  },
  tabBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    display: "flex",
    justifyContent: "space-around",
    alignItems: "center",
    background: "var(--color-surface-4)",
    borderTop: "1px solid var(--color-border)",
    padding: "10px 0 calc(14px + env(safe-area-inset-bottom))",
  },
  tabButton: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 4,
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: "4px 8px",
  },
  tabLabel: {
    fontSize: 11,
  },
  climbActionBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    background: "var(--color-surface-4)",
    borderTop: "1px solid var(--color-border)",
    padding: "18px 20px calc(22px + env(safe-area-inset-bottom))",
  },
  climbActionSideButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 52,
    height: 52,
    flexShrink: 0,
    borderRadius: 12,
    border: "1px solid var(--color-border)",
    background: "var(--color-surface-5)",
    color: "var(--color-text-primary)",
    cursor: "pointer",
  },
  climbActionSideButtonDisabled: {
    color: "var(--color-text-disabled)",
    cursor: "not-allowed",
  },
  climbActionCenter: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 8,
  },
  attemptsCounter: {
    fontSize: 15,
    fontWeight: 600,
    color: "var(--color-text-tertiary)",
  },
  attemptsCounterDisabled: {
    color: "var(--color-text-disabled)",
  },
  logAscentButton: {
    width: "100%",
    padding: "12px 16px",
    borderRadius: 10,
    border: "none",
    background: "var(--color-accent)",
    color: "var(--color-text-primary)",
    fontSize: 15,
    fontWeight: 600,
    cursor: "pointer",
  },
  logAscentButtonDisabled: {
    background: "var(--color-border)",
    color: "var(--color-text-muted)",
    cursor: "not-allowed",
  },
  sheetBackdrop: {
    position: "absolute",
    inset: 0,
    background: "rgba(0, 0, 0, 0.5)",
    transition: "opacity 0.25s ease",
    zIndex: 20,
  },
  sheet: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    width: "100%",
    maxHeight: "85%",
    overflowY: "auto",
    background: "var(--color-surface-4)",
    borderTop: "1px solid var(--color-border)",
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    padding: "10px 20px calc(24px + env(safe-area-inset-bottom))",
    // visibility is listed alongside transform so the sheet stays visible
    // for the duration of the close animation instead of vanishing
    // mid-slide, while still leaving the tab order once fully closed
    // (transform alone doesn't remove hidden elements from it — §14.13 part 3).
    transition: "transform 0.28s ease, visibility 0.28s",
    zIndex: 21,
  },
  sheetHandle: {
    width: 36,
    height: 4,
    borderRadius: 999,
    background: "var(--color-border-subtle)",
    margin: "0 auto 16px",
  },
  sheetForm: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
  },
  sheetSessionAttempts: {
    fontSize: 13,
    color: "var(--color-text-tertiary)",
    margin: "-6px 0 0",
  },
  starRow: {
    display: "flex",
    gap: 6,
    padding: "8px 10px",
    border: "1px solid transparent",
    borderRadius: 10,
    touchAction: "none",
    userSelect: "none",
    cursor: "pointer",
    width: "fit-content",
  },
  starRowInvalid: {
    border: "1px solid var(--color-danger)",
  },
  textarea: {
    background: "var(--color-surface-5)",
    border: "1px solid var(--color-border)",
    borderRadius: 10,
    padding: "10px 12px",
    fontSize: 15,
    color: "var(--color-text-primary)",
    outline: "none",
    resize: "none",
    font: "inherit",
  },
};
